# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - uses: azure/docker-login@v1
          with:
            login-server: homeless.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t homeless.azurecr.io/webhook_listener:${{ github.sha }}
            docker push homeless.azurecr.io/webhook_listener:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: dev
            dns-name-label: homeless
            image: homeless.azurecr.io/webhook_listener:${{ github.sha }}
            registry-login-server: homeless.azurecr.io
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: webhook-listener
            location: 'central us'
            ports: 3000
            secure-environment-variables: WEBHOOK_SIGNATURE=${{ secrets.WEBHOOK_SIGNATURE }} GITHUB_TOKEN=${{ secrets.GHE_TOKEN }}
            environment-variables: WEBHOOK_SSL_CERT=${{ secrets.WEBHOOK_SSL_CERT }} WEBHOOK_SSL_KEY=${{ secrets.WEBHOOK_SSL_KEY }}
